services:
  - type: web
    name: inventory-management-system
    env: node
    region: oregon
    plan: starter
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /api/auth/registration-status
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: inventory-db
          property: connectionString

databases:
  - name: inventory-db
    databaseName: inventory_management
    user: inventory_user
    region: oregon
    plan: starter